server {
      listen 80;
      server_name ibmx.net www.ibmx.net;
      return 301 https://$host$request_uri;
  }

server {
      listen 443 ssl;
      server_name ibmx.net www.ibmx.net;

      ssl_certificate /etc/letsencrypt/live/ibmx.net/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/ibmx.net/privkey.pem;

      root /usr/share/nginx/html;
      index index.html;

      location / {
          try_files $uri $uri/ /index.html;
      }
  }
